// This file is generated by npm run build:icons
 
export type IconName =
	| "app"
	| "arrow"
	| "billing"
	| "contact"
	| "cross"
	| "edit"
	| "eye"
	| "list"
	| "logout"
	| "pdf"
	| "project"
	| "search"
	| "settings"
	| "sort"
	| "table"
	| "upload";
